const INSERT_TODO = "CREATED";
const DELETE_TODO = "DELETED";
const EDIT_TODO = "UPDATED";
const ASSIGN_MEMBER_TODO = "ASSIGN_MEMBER";
const ASSIGN_PRJECT_TODO = "ASSIGN_PROJECT";
const DONE_TODO = "DONE";

module.exports = { INSERT_TODO, DELETE_TODO, EDIT_TODO, ASSIGN_MEMBER_TODO, ASSIGN_PRJECT_TODO, DONE_TODO };
